# Generated by Django 4.2.7 on 2025-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0052_deliverystatuslog_deliverymagiclink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_received_at',
            field=models.DateTimeField(blank=True, help_text='When customer confirmed receipt with photo proof', null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_proof_photo',
            field=models.ImageField(blank=True, help_text='Customer uploaded proof of delivery photo', null=True, upload_to='delivery_proof/'),
        ),
    ]
